version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:10000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 10000:10000
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - ./.env
  redis:
    image: redis:bullseye
    ports:
      - 6379:6379